version: '3.8'

services:
  ltijs:
    build: ./
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongodb/ltijs?authSource=admin
      - URL=http://localhost:3000

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: